- demo/JENKINS_HOME/jobs/docker-workflow/config.xml
- demo/plugins.txt
Shows how you can build out a test environment running Firefox inside a container, and taking advantage of Workflow 1.8 build wrappers.
Subsumes #9. @reviewbybees esp. @tfennelly
> Demo: Xvnc + Selenium

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
docker inspect -f {{.Created}} relying on go text/template do dump dates using time.Time.String(), not using expected json ISO8601 format
json Template function allows to enforce expected format, just need to skip additional json quotes
see https://github.com/docker/docker/issues/14164
> force json date format

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Allows to take into account envvars defined at node level (such as DOCKER_HOST) to execute
docker.
@reviewbybees
> [FIXED JENKINS-28611] Execute docker with the node environment

- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Accompanies https://github.com/jenkinsci/durable-task-plugin/pull/14. Ensures that we still use the fallback command-based liveness check inside Docker containers and that it works.
@reviewbybees
> [JENKINS-32264] Verifying that fallback behavior of ProcessLiveness works

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
> Log cause when stopping container

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
[JENKINS-33063](https://issues.jenkins-ci.org/browse/JENKINS-33063)
> [JENKINS-33063] Allow Image.run() to provide arguments to the container’s command

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly
Added the option to specify Dockerfile when building a container. Example:
```groovy
docker.build("jenkins-test", ".", "Dockerfile.test")
```
> docker.build with a custom Dockerfile

- pom.xml
To fix PCT against 2.x baselines. Newer version of Jenkins Test Harness fixes the build.
@reviewbybees
> Bump parent pom version to 2.9

- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
The test from #37 was broken, at least when using Docker 1.11.1:
```
+ docker run -d --rm busybox echo Hello
Conflicting options: --rm and -d
```
Also the test neglected to call `Container.stop`, so it was creating a zombie container on every run.
@reviewbybees esp. @vfarcic
> Fixing test

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
[JENKINS-31225](https://issues.jenkins-ci.org/browse/JENKINS-31225)
Possible due to baseline update in #49.
@reviewbybees esp. @jtnord
> [JENKINS-31225] Rely on $NODE_NAME, not $HOME, to see if we are inside `node {}` or not

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
It seems there are multiple formats possible for the content of /proc/self/cgroup. I modified the regex to work with the one that I see in my environment. After the patch it works as expected.
Also added a test to make sure it works with both kown variations of the format.
> Improve detection of containerized Jenkins instance

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
#54 seems to have broken the demo, for reasons I do not exactly understand; anyway, `git-bisect` led me here, and making the script less quiet does work.
@reviewbybees
> Fixing Image.inside according to make -C demo run-snapshot

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
[JENKINS-36332](https://issues.jenkins-ci.org/browse/JENKINS-36332)
I would like to apply the same command parameter that's used in  JENKINS-33063 to the "withRun" method so that I can clean up most of my containers as soon as they're finished.
Given that I also kind of need this I just PR my take on the solution :)
> [JENKINS-36332] Allow a command argument to be passed to Image.withRun

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
[JENKINS-37951](https://issues.jenkins-ci.org/browse/JENKINS-37951)
@reviewbybees
> [JENKINS-37951] Honor withTool from Image.inside

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStep.java
Provides better diagnostics for [JENKINS-38018](https://issues.jenkins-ci.org/browse/JENKINS-38018).
Downstream of https://github.com/jenkinsci/docker-commons-plugin/pull/55.
See also #71.
@reviewbybees
> [JENKINS-38018] Call newly available API

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
[JENKINS-37769](https://issues.jenkins-ci.org/browse/JENKINS-37769)
@reviewbybees
> [JENKINS-37769] Failing to stop containers cleanly, so at least stopping them quickly

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/ImageNameTokens.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
See comment in [JENKINS-32731](https://issues.jenkins-ci.org/browse/JENKINS-32731). Can simplify this plugin as of https://github.com/jenkinsci/workflow-cps-plugin/pull/33.
@reviewbybees
> [JENKINS-32731] [JENKINS-34650] Docker.groovy is already trusted

- README.md
- demo/JENKINS_HOME/jobs/docker-workflow/config.xml
- demo/README.md
- pom.xml
Will update the plugin wiki page when these changes take effect.
The link to the documentation page has been updated as well to reflect the most recent changes.
@reviewbybees
> updating display name of plugin to remove CloudBees from name.

- demo/Dockerfile
- demo/Makefile
- demo/README.md
In new Docker versions mounting the docker binary is not enough, the client needs to be installed
OS X stat parameters change slightly
Fixes #73
> [JENKINS-38835] Make demo work on newer docker versions and OS X

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
For example in RancherOS etc.
* allow stacked cgroups /docker/ID/docker/ID
* always use the last ID as container ID
* allow grouped cgroups (cpu,cpuacct)
* fix unnecessary escape
> Fix Jenkins running inside docker (inside docker)*n

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
It will warn people that docker.inside running from inside a container will not work in their case.
As seen in [this issue](https://issues.jenkins-ci.org/browse/JENKINS-33632), format of docker inspect [changed for volumes in docker 1.8 ](https://github.com/docker/docker/pull/13711).
> [JENKINS-33632] Add a warning if the detected docker version is less than v1.8

- demo/JENKINS_HOME/jobs/puller/config.xml
- demo/plugins.txt
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
[JENKINS-34276](https://issues.jenkins-ci.org/browse/JENKINS-34276)
Perhaps supersedes #51, though the ultimate goal remains unclear. I am not entirely comfortable with this fix, as the original goal of `imageName`—to make usage of custom registries transparent—is unmet, and may be unattainable.
My inclination is to deprecate the whole DSL as more confusing than helpful. It does not add much value beyond the plugin’s provided steps, except this registry prefix handling, and the possibly unused fingerprinting system. Certainly the number of PRs to review would drop; people would be free to share and use public libraries as conveniences, or not.
@reviewbybees
> [JENKINS-34276] Allow Image.inside to run with either a local or registry-prefixed name

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerTestUtil.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
[JENKINS-37719](https://issues.jenkins-ci.org/browse/JENKINS-37719)
https://github.com/jenkinsci/workflow-cps-plugin/pull/102 and https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/30 are also helpful but this patch in isolation suffices to fix the problem, at least to the extent I am able to reproduce it by simply forcing the Docker daemon to hang.
@reviewbybees
> [JENKINS-37719] Apply a timeout to all Docker CLI operations

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
Used in the course of developing https://github.com/jenkinsci/acceptance-test-harness/pull/272. Might be considered too chatty, but given the confusion attending problems like that (purportedly) fixed in #82, it seems better to err on the side of being clear about why we are running in a certain mode.
@reviewbybees
> Print diagnostics to the build log explaining why --volumes-from is or is not being used

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
[JENKINS-43328](https://issues.jenkins-ci.org/browse/JENKINS-43328)
> [JENKINS-43328] Detect container ID when run with --parent-group

- src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly
If anyone prefers 'agent' alone that's OK, I tend to feel like 'Jenkins agent' reads a little better in this context.
> Replace usage of 'slave' with 'Jenkins agent'

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
Removes space from **getVolumes()** format parameter to avoid error as mentioned in issue https://github.com/moby/moby/issues/8792
> Stray whitespace in DockerClient.getVolumes format string can cause errors

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
'docker run' command does not work if Jenkins has empty environment variables.
```
java.io.IOException: Failed to run image 'maven:3.3.3'. Error: invalid argument "=" for e: invalid environment variable: =
See 'docker run --help'.
```
> remove empty EnvVars to execute 'docker run' command

- src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerTestUtil.java
[JENKINS-44609](https://issues.jenkins-ci.org/browse/JENKINS-44609)
Instead of grabbing the image name of the first FROM statement in a Dockerfile, now will return the last one.
> [FIXED JENKINS-44609] Docker multi-stage builds no longer throw errors

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
This blacklists certain environment variables to be passed into docker
run via the -e flags:
- PATH
- A bunch of LD_ vars
[JENKINS-43590](https://issues.jenkins-ci.org/browse/JENKINS-43590) docker.inside()'s -e flags are random
This is a better solution than #96
> Blacklist EnvVars for docker run -e

- .editorconfig
- src/main/java/org/jenkinsci/plugins/docker/workflow/DockerUtils.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/test/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStepTest.java
Fixes JENKINS-46105 Docker 17.05 ARG in FROM breaks docker inspect
https://issues.jenkins-ci.org/browse/JENKINS-46105
Introduce command line parsing using [CommandLine](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.ant/ant/1.9.5/org/apache/tools/ant/types/Commandline.java) from Ant.
Then extract all --build-arg and pass it to the FromFingerprintStep to replace placeholders in the FROM image name.
> JENKINS-46105 Docker 17.05 ARG in FROM breaks docker inspect

- src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
@lucamilanesio [seems to have copied these sources](https://github.com/GerritForge/gerrit-plugin/commit/61c0a66f2e3ac8fc4958f4d2842a32628754f36e) for his own plugin, [spreading the madness](https://groups.google.com/d/msg/jenkinsci-dev/E3pvb0WH4Ls/E3n9BgzaEAAJ), and I recall others poking around here too. I would delete it all if I could, but it is too late for that. (Unless the `Step`s could be moved to a new `pipeline-docker` plugin and `docker-workflow` to retain only the DSL?)
@reviewbybees
> Adding warnings to sources

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
I got https://github.com/moby/moby/issues/8917 approved and corresponding PR merged for docker 17.12, so we now have a solution for `dir()` support in docker-pipeline
Also used `--env` to support withEnvironment, to avoid the `env` command hack.
> [FIX JENKINS-33510] exec --workdir has been introduced in docker 17.12

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
See discussion on https://github.com/jenkinsci/docker-workflow-plugin/pull/85
> [FIXED JENKINS-41316] Switch 'inside' back to CMD, detect if entrypoint was badly designed

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
Hi, docker build commands accept `-f <filepath>`, `--file <filepath>` and `--file=<filepath>`, but I found `Docker.build` method can't handle the `--file=<filepath>` argument. I use `startsWith` to check the argument, and set correct dockerfile path.
> Accept `--file=<filepath>` to `build` method

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
Resolves an issue with newer versions of docker where the `--force` tag fails and tags are not correctly registered.
> [JENKINS-42152] Do not use --force when tagging images

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStep.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStep/config.jelly
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Downstream of https://github.com/jenkinsci/docker-commons-plugin/pull/67.
@reviewbybees
> [JENKINS-38018] Use docker-login wherever possible for registry credentials

- pom.xml
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
Amends #133 to pick up https://github.com/jenkinsci/docker-commons-plugin/pull/67, and generally gets things ready for a release.
> [JENKINS-38018] Preparing for release

- src/main/java/org/jenkinsci/plugins/docker/workflow/DockerUtils.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/Dockerfile.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerUtilsTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerfileTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStepTest.java
- src/test/resources/Dockerfile-defaultArgs
- src/test/resources/Dockerfile-withArgs
This PR adds the ARG values from the Dockerfile instructions to the buildArgs collection added in the PR #118 
Using this as  Dockerfile
```Dockerfile
ARG REGISTRY_URL
ARG TAG=latest
FROM ${REGISTRY_URL}hello-world:${TAG}
```
So even after the PR #118 I'm getting the `docker inspect` error in the FromFingerprintStep from the issue https://issues.jenkins-ci.org/browse/JENKINS-46105.
To get a successful build I did a workaround adding the build-args (REGISTRY_URL empty is necessary).
```
docker.build("image_name", "--build-arg REGISTRY_URL= --build-arg TAG=${version} .")
```
With this PR we are able to build the Dockerfile above without passing any --build-arg to the command.
It's reading the ARG instructions from the Dockerfile and adding to buildArgs collection as default values. When a …
> Add ARG Dockerfile values to the buildArgs collection

- src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly
This has bitten me quite a few times, not doing image.pull() before image.inside() and similar commands can results in strange behaviors if Jenkins agents have different image versions cached locally. This commit adds a clarification in the documentation.
> Clarified consequences of not doing image.pull()

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
[JENKINS-56674](https://issues.jenkins-ci.org/browse/JENKINS-56674) Subsumes #166 by @vkravets.
I consider this a security hardening. Suppose you have some plugin which uses `Launcher`, calls `env` on a sensitive variable, and does _not_ use `.quiet(true)`. Normally it will look like this in the log:
$ command with args
If you wrapped in `withDockerContainer` before this fix:
$ docker exec --env VAR=value abc123def456 command with args
and after:
$ docker exec --env ******** abc123def456 command with args
Or for old versions of Docker,
$ docker exec abc123def456 env VAR=value command with args
vs.
$ docker exec abc123def456 env ******** command with args
> [JENKINS-56674] Masking of environment variables passed to docker exec

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Resolves https://issues.jenkins-ci.org/browse/JENKINS-56674
I would like to propose and show which issue exists with masked env variables during such case
```
node {
withDockerContainer('ubuntu') {
env.TEST_PWD = 'pwd12345'
withDockerContainer('ubuntu') {
withDockerContainer('ubuntu') {
sh('echo test')
}
}
}
}
```
So the output of job will have include env variable which can contains sensitive data (first part of docker exec):
```
6.514 [prj #1] [Pipeline] node
6.617 [prj #1] Running on master in /Users/vkravets/work/my/docker-workflow-plugin/tmp/workspace/prj
6.617 [prj #1] [Pipeline] {
7.814 [prj #1] [Pipeline] withDockerContainer
7.814 [prj #1] Jenkins does not seem to be running inside a container
7.815 [prj #1] $ docker run -t -d -u 501:20 -w …
```
> [JENKINS-56674] Mask environment variable if they passed in case of inside docker image run

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStepTest.java
See [JENKINS-48437](https://issues.jenkins-ci.org/browse/JENKINS-48437). Subsumes #141 to pick up https://github.com/jenkinsci/docker-commons-plugin/pull/74. 
Expands on the existing tests to show that `Credentials.USE_ITEM` (`Job.CONFIGURE`) is the key permission required for the new APIs to be an improvement.
Effective diff from #141 is https://github.com/Dohbedoh/docker-workflow-plugin/compare/JENKINS-48437...dwnusbaum:JENKINS-48437
> [JENKINS-48437] Use new docker-commons API and pass the Run to retrieve the token

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStepTest.java
[JENKINS-48437](https://issues.jenkins-ci.org/browse/JENKINS-48437)
Consume a new API introduced in https://github.com/jenkinsci/docker-commons-plugin/pull/68 that accepts a `Run` to resolve the credentials ID.
> [JENKINS-48437] Use the new API passing the Run to retrieve the token

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
https://issues.jenkins-ci.org/browse/JENKINS-46636
This works around the lack of --workdir for "docker exec" in versions earlier than 17.12.
It wraps an additional shell around the sh() command which issues a "cd" before delegating.
> JENKINS-46636 Fix dir() for older docker

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroup.java
If you currently run a [Jenkinsfile runner within a Docker container within GitHub Actions](https://blogs.sap.com/2019/09/13/running-sap-cloud-sdk-pipeline-on-github-actions/), spawning docker containers from this Jenkins instance will not detect that we are already running in a docker container:
> [Pipeline] withDockerContainer
Jenkins does not seem to be running inside a container
Looking into https://github.com/jenkinsci/docker-workflow-plugin/blob/50ad50bad2ee14eb73d1ae3ef1058b8ad76c9e5d/src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java#L328 and https://github.com/jenkinsci/docker-workflow-plugin/blob/50ad50bad2ee14eb73d1ae3ef1058b8ad76c9e5d/src/main/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroup.java#L52, it looks as if Jenkins is parsing …
> Add Container ID detection for GitHub Actions

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly
Automatic fingerprinting was removed in PR #180, but for some reason Image.inside() was left unchanged.
This is a for from a pull request in docker-common plugin, https://github.com/jenkinsci/docker-commons-plugin/pull/85
Also removes incorrect documentation that was missed in PR #180.
> Remove automatic fingerprinting from Image.inside() step.

- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Amends #86 & #107 to not let the test run to full 3m timeout when `sudo` prompts for authentication, as it does on some PCT builders.
> Impose a 15s timeout on sudo operations

- src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/FolderConfig/config.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfig/config.groovy
The section header `Declarative Pipeline (Docker)` in the UI can cause the properties folder to render incorrectly when other plugins are installed.
CC @dwnusbaum
> Remove section header from folder properties in jelly.

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
This PR contains a change to remove the variable "=" when the plugin executes the _exec_ command.
This problem appears after executing a sh command inside the withDockerContainer block. Activate the diagnosis and the error was:
```
invalid argument "=" for "-e, --env" flag: invalid environment variable: =
See 'docker exec --help'.
```
Also, I activated the class Logger and found the empty variable from message _FINE org.jenkinsci.plugins.docker.workflow.WithContainerStep (exec) reduced environment: [**=**,....]_.
I was looking for information about this and found a PR #101 that fixed a similar problem but for the run command.
For now I am using as an alternative to run the withDockerContainer function with a withEnv to override the invalid environment variable. For example:
```groovy …
```
> JENKINS-52264 The variable "=" is removed when the exec command is executed

- pom.xml
- src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DeclarativeDockerUtilsTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerBasicModelDefTest.java
updating jenkins version to 2.176.4, supersedes #214
> update to 2.176.4

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroup.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroupTest.java
Bugfix for JENKINS-57129
java.io.IOException: 
Unexpected cgroup syntax, https://issues.jenkins-ci.org/browse/JENKINS-57129
The old parser is not universal and does not take in account some variants like this:
/kubepods/burstable/pod1fe52ba4-5709-11ea-9ee3-00505682780f/d65c8853fa45d139ce95d5c2b68a6e4aa8da83894d8eb0396cd6edd1c134c97c/user.slice
> JENKINS-57129 Bugfix for : Unexpected cgroup syntax

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
Added a system property which makes it possible to skip removal of containers after stop has been issued (either through container.stop() or during exit of within() step). This is useful for users (like us) which produces very large build trees in our containers, and in some situations, hit the timeout. Rather than extending the timeout we would like our builds to finish fast and then handle cleanup with separate janitor-job.
> Add ability to skip removal of container after docker stop via the `org.jenkinsci.plugins.docker.workflow.client.DockerClient.SKIP_RM_ON_STOP`property

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/WindowsDockerClient.java
**Problem description:**
For Windows there is a problem with Javas ProcessBuilder and arguments that contain spaces and contain double quotes as ProcessBuilder adds double quotes around such argument.
See e.g. https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6511002 and https://stackoverflow.com/questions/12124935/processbuilder-adds-extra-quotes-to-command-line
**Solution:**
For Windows all environment variables (only values) are escaped (currently only escapes quotes). No changes made to the Linux (and others) code as I could only reproduce this behavior with a Windows node.
**Notes:**
- This is nearly the same as #215 but does not add additional quotes around every environment variable value and also applies this do Windows only.
- I build this changes locally and tested it in some …
> escape double quotes in env variables under windows

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
Based on c97bf2305ccf8c8dc1fcc91e329bf81a41c14638 from #220 which quoted "docker run" env-vars, this addresses [JENKINS-64751](https://issues.jenkins.io/browse/JENKINS-64751) and [JENKINS-65933](https://issues.jenkins.io/browse/JENKINS-65933).
I have not included any tests, as my understanding from #215 is that we do not have test infrastructure that supports docker-execution tests on Windows, similarly to #220.
> [JENKINS-64751] Quote "docker exec" env-vars on Windows

- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
Environment variables need an other syntax for be usable on windows `bat`.
This PR fixes [JENKINS-67578](https://issues.jenkins.io/browse/JENKINS-67578) and [JENKINS-67589](https://issues.jenkins.io/browse/JENKINS-67589).
Commit b3a69962919bb51c7e5f18f384236518e09909be has broken this plugin for windows users.
> fix: use correct syntax for environment variable

- src/main/java/org/jenkinsci/plugins/docker/workflow/AbstractEndpointStepExecution.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/ImageAction.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/ImageNameTokens.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/RunFingerprintStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroup.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/LaunchResult.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/client/WindowsDockerClient.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/AbstractDockerAgent.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/DeclarativeDockerUtils.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerLabelProvider.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerPipeline.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerPipelineFromDockerfile.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerPropertiesProvider.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/FolderConfig.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfig.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStepTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerDirectiveGeneratorTest.java
Removes JSR 305 and adds missing annotations.
There were two `assert`s, which are replaced by an actual check too.
---------------------------
> Remove JSR 305

- pom.xml
- src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java
- src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/AbstractDockerAgent.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStepTest.java
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/dockerPullLocalImage.groovy
See https://github.com/jenkinsci/workflow-cps-plugin/pull/538 and https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/529. This would not be needed except for the fact that `DockerPipelineFromDockerfileScript.groovy` and `DockerPipelineScript.groovy` inherit from `AbstractDockerPipelineScript.groovy`, which does not correspond to any concrete subclass of `WithScriptDescribable`.
> Use GroovySourceFileAllowlist to adapt to SECURITY-359 changes

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
I saw these flake in #256 and didn't think much of it, but then I saw them also fail in https://github.com/jenkinsci/docker-workflow-plugin/pull/253, and took a look. There seem to be a lot of problems with our use of `ps`.
The real head scratcher for me though is that the tests pass locally with `httpd:2.4.12`. They only fail if I use `httpd:2.4.35` or newer (which I believe is due to the switch to a `-slim` version of Debian in https://github.com/docker-library/httpd/pull/113 which _removes_ `ps` from the container entirely, but it is hard to track things down because that repo does not have tags/releases). If I do update to 2.4.35 or newer then I get the exact error messages seen in CI. Is something in the CI environment forcing newer images to be used? Is that even possible?
> Fix WithContainerStepTest.stop and WithContainerStepTest.death

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
- src/test/resources/org/jenkinsci/plugins/docker/workflow/agent-with-docker/Dockerfile
Trying to see if the likes of #241 / #276 can be mechanically reproduced both locally and in CI.
> [JENKINS-64608] Fix cgroup v2 detection of Docker CLI running inside a container

- src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
- src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
For example, the following Jenkinsfile:
```groovy
pipeline {
agent {
docker {
image 'docker:dind'
}
}
}
```
Will create the container based on `docker:dind`, which declares a `VOLUME` that docker creates automatically (this is called anonymous volumes).
However, due to the way how Jenkins deletes the container after finishing the build, it will leave the anonymous volume dangling on the agent.
Over time, this can cause issues as these volumes can consume a high amount of disk space and there's no current Jenkins mechanism to delete them other than "manually".
This now aligns with the behavior of `docker run --rm`, which not only deletes the container itself but also its anonymous volumes.
Fixes [JENKINS-70132](https://issues.jenkins.io/browse/JENKINS-70132)
> [JENKINS-70132] Remove anonymous volumes when removing the container

- src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-793/2/console (https://github.com/jenkinsci/acceptance-test-harness/pull/793) failed due to an infrastructure problem:
```
java.io.IOException: Unable to create live FilePath for EC2 (aws-us-east-2) - High memory ubuntu 20.04 (i-0ff0c81a874559911)
at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:66)
at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:48)
at org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:95)
at org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(ContextVariableSet.java:139)
at org.jenkinsci.plugins.workflow.cps.CpsThread.getContextVariable(CpsThread.java:137)
at …
```
> Do not pass a null `Launcher` to `DockerClient`

- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
- src/test/java/org/jenkinsci/plugins/docker/workflow/client/WindowsDockerClientTest.java
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDocker.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDocker.json
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerContainerPerStage.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerDontReuseNode.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerEnvSpecLabel.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerEnvTest.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerReuseNode.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerWithCreds.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerWithEmptyDockerArgs.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerWithNullDockerArgs.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerWithRegistryNoCreds.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentDockerWithoutContainerPerStage.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/agentInStageAutoCheckout.groovy
- src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/nonExistentDockerImage.groovy
Indeed since Docker 26 the image in the old v1 format are no longer run by default (it used to be deprecated but tolerated for years). Fix this by hardcoding the very latest httpd docker image version as of today.
If you are interested by the actual deprecation description on docker side, it's this one: https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1
If fixes errors like this that we have with the current non-regressions tests (extracted from your CI: https://ci.jenkins.io/job/Plugins/job/docker-workflow-plugin/job/PR-312/1/pipeline-console/?selected-node=33)
```
10:52:10  [Pipeline] withEnv
10:52:10  [Pipeline] {
10:52:10  [Pipeline] sh
10:52:10  + docker inspect -f . httpd:2.4.12
10:52:10  
10:52:10  Error: No such object: httpd:2.4.12 …
```
> Migrate tests to the very latest httpd docker image to unbreak tests.

- src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java
Test coverage added in #141 gave the alarming impression that the registry password was printed in plain text to the build log when running `docker login`. It is in fact masked, and has been since https://github.com/jenkinsci/docker-commons-plugin/pull/67 (despite https://github.com/jenkinsci/docker-commons-plugin/pull/108).
> Clarifying password masking in `RegistryEndpointStepTest`

- src/test/java/org/jenkinsci/plugins/docker/workflow/DockerTestUtil.java
The plugin BOM agents seem to have the `docker` command available but the user running the agent is not authorized to use the `docker` command.  Previously that was detected by calling `docker ps` and detecting the failure.
Restores a change made in
* https://github.com/jenkinsci/docker-workflow-plugin/pull/331
Plugin BOM draft pull request to check it on weekly:
* https://github.com/jenkinsci/bom/pull/4473
Confirmed that I could see the same failure on a local computer as is seen on https://ci.jenkins.io/job/Tools/job/bom/job/master/3968/testReport/org.jenkinsci.plugins.docker.workflow/DockerDSLTest/
The computer had Docker CE installed by the specific user running the test did not have permission to access Docker.  Prior to this change, the tests failed with the message:
```
CANNOT …
```
> Use docker ps to detect absence of docker permissions

- pom.xml
- src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/AbstractDockerPipelineScript.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/DockerPipelineFromDockerfileScript.groovy
- src/main/resources/org/jenkinsci/plugins/docker/workflow/declarative/DockerPipelineScript.groovy
Adapts to https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/762, which is unfortunately incompatible in that `DeclarativeDockerUtils.getLabelScript` is going to return a new type of object. (Due to the complex mixture of CPS-transformed Groovy sources and Java APIs, it did not seem feasible to make that a compatible change.)
> Adapt to Declarative change

- src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerAgentTest.java
Noticed a PCT failure when trying to set a Docker login for the CI machine to evade rate limits. https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/308 was hard-coding @joseblas’s personal account name.
> Skip `agentDockerWithCreds` unless both `docker.username` and `docker.password` are set

- pom.xml
- src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java
https://github.com/jenkinsci/ssh-agents-plugin/pull/607 https://github.com/jenkinsci/docker-workflow-plugin/pull/351#discussion_r2114849203
> Demonstrating use of `OutboundAgent`
