src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java
According to: https://github.com/jenkinsci/script-security-plugin/pull/15
@reviewbybees
=> Reordering whitelist

demo/Makefile
=> Makefile cleanup

src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/RunFingerprintStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/LaunchResult.java
Main change - prevent NPEs on **docker inspect** call errors
@reviewbybees @jglick
=> FindBugs: Cleanup null checks and serialVersionUIDs

demo/JENKINS_HOME/jobs/docker-workflow/config.xml
HTML markup is disabled by default, so replace the hyperlink by a plain text
@reviewbybees
=> Fixed the job description in the demo.

demo/run-demo.sh
[JENKINS-28813](https://issues.jenkins-ci.org/browse/JENKINS-28813)
@reviewbybees esp. @tfennelly and @oleg-nenashev
=> [JENKINS-28813] Restart the registry if it crashes

.gitignore, pom.xml
So Jenkins can pick up the results
@reviewbybees
=> Configure findbugs xml output

src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
Supersedes #18. There were two issues with this test.
First, if you `docker rmi hello-world` before running, and did not `docker pull hello-world`, you get
```
Step 0 : FROM hello-world@91c95931e552b11604fea91c2f537284149ec32fff0f700a4769cfd31d7696ae
Pulling repository hello-world
Tag 91c95931e552b11604fea91c2f537284149ec32fff0f700a4769cfd31d7696ae not found in repository hello-world
```
It seems that `docker-build` has a bug (as of the 1.7.1 client anyway): it accepts image hashes in place of tags, and normally it will do an implicit `docker-pull` on the ancestor image if it is not found locally, yet this does not work in the case of a hash. It misinterprets the hash as a tag in this stage.
Second, the test was originally written to try to build a _predictable_ image ID. For all the talk …
=> Fixing DockerDSLTest.build

demo/Makefile, demo/run-demo.sh
=> Demo fixups

src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
=> Fix findbugs issues

demo/Dockerfile_release, demo/Dockerfile_snapshot
Needed to evaluate #23.
@reviewbybees
=> Update demo image to be buildable once again

README.md, demo/JENKINS_HOME/jobs/docker-workflow/config.xml, pom.xml, src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/main/resources/index.jelly, src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
The wiki page was created https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Pipeline+Plugin
@reviewbybees
=> Renaming Workflow to Pipeline

pom.xml
Pipeline and Findbugs dependencies were updated and findbugs plugin configuration reviewed.
@reviewbybees
=> Pipeline and Findbugs dependencies were updated

demo/README.md
=> More renaming Workflow to Pipeline

src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
Prerequisite for Maven release.
@reviewbybees
=> Make test more reliable

pom.xml, src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy, src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStepTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Various changes in recent Docker releases caused the existing tests to fail.
@reviewbybees
=> Make tests pass when using Docker 1.10.1

pom.xml, src/main/java/org/jenkinsci/plugins/docker/workflow/AbstractEndpointStepExecution.java, src/main/java/org/jenkinsci/plugins/docker/workflow/DockerDSL.java, src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/RegistryEndpointStepTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/ServerEndpointStepTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
[JENKINS-27152](https://issues.jenkins-ci.org/browse/JENKINS-27152)
Matches https://github.com/jenkinsci/durable-task-plugin/pull/19.
@reviewbybees
=> [JENKINS-27152] Mount workspace@tmp

src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java, src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
[JENKINS-33510](https://issues.jenkins-ci.org/browse/JENKINS-33510)
@reviewbybees esp. @cyrille-leclerc & @ndeloof
=> [JENKINS-33510] At least clearly diagnose failure to set CWD

src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy, src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
Can be useful when the container is started with random port mapping.
@reviewbybees
=> Display ports exposed and mapped by container

src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
Corrects mistakes in #31.
@reviewbybees and @emmanuel099
=> Mistakes in #31

src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
=> /proc/self/cgroup only exists on Linux

pom.xml, src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
=> Fixing some old TODOs

src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy, src/main/resources/org/jenkinsci/plugins/docker/workflow/DockerDSL/help.jelly, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
[JENKINS-34050](https://issues.jenkins-ci.org/browse/JENKINS-34050)
=> [JENKINS-34050] docker.build: custom Dockerfile path

pom.xml, src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
=> [JENKINS-26133] Taking advantage of returnStdout to simplify DSL implementation a little

src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/RunFingerprintStep.java
Inspired by https://github.com/jenkinsci/workflow-multibranch-plugin/issues/29 though not pretending to address a similar issue.
@reviewbybees
=> Use AbstractSynchronousNonBlockingStepExecution for steps which run the Docker client

src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
Integrates #40 & #54.
@reviewbybees
=> Simplifying Container.port with returnStdout

demo/Dockerfile, demo/repo/flow.groovy, src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy
Subsumes #61. Incorporates https://github.com/jenkinsci/workflow-aggregator-plugin/pull/9.
@reviewbybees
=> Demo updates

src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
[JENKINS-37987](https://issues.jenkins-ci.org/browse/JENKINS-37987)
@reviewbybees esp. @alvarolobato
=> [JENKINS-37987] Override ENTRYPOINT, not just command, for WithContainerStep

demo/Dockerfile, demo/Makefile, demo/README.md, demo/plugins.txt, demo/run-demo.sh
While working on #68 and #69 I found some miscellaneous things to be improved in the demo, mainly drawing from experience with https://github.com/jenkinsci/parallel-test-executor-plugin/pull/20.
@reviewbybees
=> Demo tweaks

src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
Noticed while creating #68. Amends #31.
@reviewbybees
=> DockerClient.getVolumes fix

src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
[JENKINS-40101](https://issues.jenkins-ci.org/browse/JENKINS-40101)
Have not tracked down the cause yet, but at least here is a test proving it.
@reviewbybees
=> [JENKINS-40101] Reproduced bug in test

src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java
[JENKINS-43222](https://issues.jenkins-ci.org/browse/JENKINS-43222)
=> [JENKINS-43222] run docker cli with full environment for running commands on node.

src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerTestUtil.java, src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
[JENKINS-42322](https://issues.jenkins-ci.org/browse/JENKINS-42322)
Supersedes #100.
@reviewbybees
=> [JENKINS-42322] Increased default timeout for docker client operations

src/test/java/org/jenkinsci/plugins/docker/workflow/WithContainerStepTest.java
Required by https://github.com/jenkinsci/durable-task-plugin/pull/49.
@reviewbybees
=> [JENKINS-47791] Making WithContainerStepTest.death not assume the existence of a pid file

src/main/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroup.java, src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java, src/test/java/org/jenkinsci/plugins/docker/workflow/client/ControlGroupTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/client/DockerClientTest.java
regular expression are powerful but hard to maintain.
see discussion on https://github.com/jenkinsci/docker-workflow-plugin/pull/120
=> introduce ControlGroup to handle containerID extraction

src/main/java/org/jenkinsci/plugins/docker/workflow/client/DockerClient.java
Adding space to exception message when inspecting container.
=> Add space to exception message when inspecting container

.mvn/extensions.xml, pom.xml
Similar reasoning to https://github.com/jenkinsci/ssh-agent-plugin/pull/26.
=> Updated parent

src/main/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep.java, src/main/java/org/jenkinsci/plugins/docker/workflow/RunFingerprintStep.java, src/main/resources/org/jenkinsci/plugins/docker/workflow/Docker.groovy, src/main/resources/org/jenkinsci/plugins/docker/workflow/FromFingerprintStep/help.html, src/main/resources/org/jenkinsci/plugins/docker/workflow/RunFingerprintStep/help.html, src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java, src/test/java/org/jenkinsci/plugins/docker/workflow/FromFingerprintStepTest.java
=> Deprecate and remove FromFingerprintStep

src/test/java/org/jenkinsci/plugins/docker/workflow/DockerTestUtil.java
Improve readability by avoiding horizontal scrolling.
=> Split long line

src/main/java/org/jenkinsci/plugins/docker/workflow/Dockerfile.java
=> Use try-with-resource

.github/release-drafter.yml
=> Enable Release Drafter in the Repository

README.md
=> Move changelog to GitHub, add badges for the plugin site and release stats

src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/FolderConfig.java, src/main/java/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfig.java, src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfigTest.java, src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfigTest/oldPackages/jobs/d/config.xml, src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/GlobalConfigTest/oldPackages/org.jenkinsci.plugins.pipeline.modeldefinition.config.GlobalConfig.xml
Amends #202 due to loss of data.
@Smasherr if CI passes here, there should be an incremental download link from the GitHub status. You can grab the `*.hpi` and use **Plugin Manager » Advanced » Upload** to run it.
=> [JENKINS-58732] Migrate GlobalConfig & FolderConfig serial forms

src/test/java/org/jenkinsci/plugins/docker/workflow/DockerDSLTest.java
The testing that the fix for SECURITY-1878 also covers [JENKINS-57366](https://issues.jenkins.io/browse/JENKINS-57366) which it does.
=> [JENKINS-57366] Testing that the security fix covered this

pom.xml
The BOM now contains a newer version.
=> Use BOM model definition plugin version

.mvn/extensions.xml, Jenkinsfile, pom.xml, src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerDirectiveGeneratorTest.java
Closes #296.
```[tasklist]
```
=> Refresh plugin for June 2023

src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DockerAgentTest.java, src/test/resources/org/jenkinsci/plugins/docker/workflow/declarative/userHandbookDockerfile.groovy
https://github.com/jenkinsci/docker-workflow-plugin/pull/57#issuecomment-1507755385
=> Verify the basic sample from the user handbook

Jenkinsfile, pom.xml, src/test/java/org/jenkinsci/plugins/docker/workflow/declarative/DeclarativeDockerUtilsTest.java, src/test/resources/org/jenkinsci/plugins/docker/workflow/agent-with-docker/Dockerfile
Due to the FormException, quick fix is to add a static block
Also update Jenkins to match archetype (expect the custom label)
Just compile. Will rely on CI for tests
=> Require 2.452.4 and fix test compilation
